runtime: java
env: flex
env_variables:
  MY_VAR: "my value"

resources:
  cpu: 2
  memory_gb: 1.5
  disk_size_gb: 10
  
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6